{dede:field name='keywords'}{/dede:field}
{dede:field name='description'}{/dede:field}
{dede:field name='title'}缓一天，明天再更{/dede:field}
{dede:field name='writer'}{/dede:field}
{dede:field name='source'}{/dede:field}
{dede:field name='pubdate'}{/dede:field}
{dede:field name='body'}第七篇结束后，番茄也不想请假，所以就直接开始写第八篇~~~不过写起来的确颇为吃力。<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;磨刀不误砍柴工，还是请假一天，细细梳理，将第八篇的各条线、情节铺垫都梳理下。<br /><br />&nbsp;&nbsp;&nbsp;&nbsp;明天再恢复更新~~~~欠章会在近期择期补掉。(未完待续。。){/dede:field}
{dede:field name='litpic'}{/dede:field}
