{dede:noteinfo notename="顶点小说+雪鹰领主" channelid="1" macthtype="string"
    refurl="http://" sourcelang="gb2312" cosort="desc"
  isref="no" exptime="10" usemore="1" /}
{dede:listrule sourcetype="batch" rssurl="http://" regxurl="(#)"
startid="1" endid="" addv="1" urlrule="area" musthas=".html"
 nothas="" listpic="1" usemore="1"}
    {dede:addurls}{/dede:addurls}
    {dede:batchrule}[(#)=>http://www.23wx.com/html/55/55519/; (*)=>1-2; typeid=>500]{/dede:batchrule}
    {dede:regxrule}{/dede:regxrule}
    {dede:areastart}<table cellspacing="1"{/dede:areastart}
    {dede:areaend}<dd id="foottips">{/dede:areaend}
{/dede:listrule}
