<?php  exit();
/*
Page: /
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-03-31 17:18:55
*/
?>
<?php  exit();
/*
Page: /phpmyadmin/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-03-31 17:19:49
*/
?>
<?php  exit();
/*
Page: /phpmyadmin/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-03-31 17:22:33
*/
?>
<?php  exit();
/*
Page: /phpmyadmin/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-03-31 17:23:44
*/
?>
<?php  exit();
/*
Page: /phpmyadmin/
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-03-31 17:23:56
*/
?>
<?php  exit();
/*
Page: /
Error: DedeCms错误警告：<font color='red'>连接数据库失败，可能数据库密码不对或数据库服务器出错！</font>
Time2016-03-31 17:30:57
*/
?>
